return {
  -- Base
  CursorLine = { fg = C.none, bg = C.blue_4},
  LineNr = { fg = C.grey_1, bg = C.none },
  CursorLineNr = { fg = C.blue, bg = C.none },
  -- Notify
  NotifyERRORBorder = { fg = C.red },
  NotifyWARNBorder = { fg = C.orange_1 },
  NotifyINFOBorder = { fg = C.green },
  NotifyDEBUGBorder = { fg = C.cyan },
  NotifyTRACERBorder = { fg = C.purple },
  NotifyERRORIcon = { fg = C.red },
  NotifyWARNIcon = { fg = C.orange_1 },
  NotifyINFOIcon = { fg = C.green },
  NotifyDEBUGIcon = { fg = C.cyan },
  NotifyTRACEIcon = { fg = C.purple },
  NotifyERRORTitle = { fg = C.red },
  NotifyWARNTitle = { fg = C.orange_1 },
  NotifyINFOTitle = { fg = C.green },
  NotifyDEBUGTitle = { fg = C.cyan },
  NotifyTRACETitle = { fg = C.purple },
  NotifyERRORBody = { fg = C.fg },
  NotifyWARNBody = { fg = C.fg },
  NotifyINFOBody = { fg = C.green },
  NotifyDEBUGBody = { fg = C.fg },
  NotifyTRACEBody = { fg = C.fg },
  NotifyLogTime = { fg = C.grey_2 },
  NotifyLogTitle = { fg = C.green },
  -- BufferLine
  BufferLineBufferVisible = { fg = C.blue, bg = C.none },
  BufferLineBufferSelected = { fg = C.blue, bg = C.bg, bold = false },
  BufferLineTab = { fg = C.blue, bg = C.bg },
  BufferLineTabSelected = { fg = C.fg, bg = C.bg },
  BufferLineTabClose = { fg = C.blue, bg = C.bg },
  BufferLineIndicatorSelected = { fg = C.bg, bg = C.bg },
  BufferLineCloseButtonVisible = { fg = C.blue, bg = C.bg },
  BufferLineCloseButtonSelected = { fg = C.blue, bg = C.bg },
  BufferLineModifiedVisible = { fg = C.fg, bg = C.bg },
  BufferLineModifiedSelected = { fg = C.green_2, bg = C.bg },
  BufferLineError = { fg = C.red_1, bg = C.red_1 },
  BufferLineErrorDiagnostic = { fg = C.red_1, bg = C.red_1 },
  -- TreeSitter
  TSError = { fg = C.red },
  TSPunctDelimiter = { fg = C.fg },
  TSPunctBracket = { fg = C.fg },
  TSPunctSpecial = { fg = C.fg },
  TSConstant = { fg = C.yellow },
  TSConstBuiltin = { fg = C.orange },
  TSConstMacro = { fg = C.red },
  TSStringRegex = { fg = C.green },
  TSString = { fg = C.green },
  TSStringEscap = { fg = C.red },
  TSCharacter = { fg = C.green },
  TSNumber = { fg = C.orange },
  TSBoolean = { fg = C.orange },
  TSFloat = { fg = C.green },
  TSAnnotation = { fg = C.yellow },
  TSAttribute = { fg = C.red },
  TSNamespace = { fg = C.purple },
  TSFuncBuiltin = { fg = C.blue },
  TSFunction = { fg = C.blue },
  TSFuncMacro = { fg = C.yellow },
  TSParameter = { fg = C.red },
  TSParameterReference = { fg = C.cyan },
  TSMethod = { fg = C.blue },
  TSField = { fg = C.red },
  TSProperty = { fg = C.yellow },
  TSConstructor = { fg = C.yellow },
  TSConditional = { fg = C.purple },
  TSRepeat = { fg = C.purple },
  TSLabel = { fg = C.blue },
  TSKeyword = { fg = C.purple },
  TSKeywordFunction = { fg = C.purple },
  TSKeywordOperator = { fg = C.purple },
  TSOperator = { fg = C.cyan },
  TSException = { fg = C.purple },
  TSType = { fg = C.blue },
  TSTypeBuiltin = { fg = C.blue },
  TSStructure = { fg = C.purple },
  TSInclude = { fg = C.purple },
  TSVariable = { fg = C.blue },
  TSVariableBuiltin = { fg = C.yellow },
  TSText = { fg = C.fg },
  TSTextReference = { fg = C.yellow },
  TSStrong = { fg = C.blue, style = "bold" },
  TSEmphasis = { fg = C.purple, style = "italic" },
  TSUnderline = { fg = C.fg },
  TSTitle = { fg = C.fg },
  TSLiteral = { fg = C.fg },
  TSURI = { fg = C.green },
  TSTag = { fg = C.red },
  TSTagDelimiter = { fg = C.fg },
  markdownTSNone = { fg = C.fg },
  markdownTSTitle = { fg = C.red },
  markdownTSLiteral = { fg = C.green },
  markdownTSPunctSpecial = { fg = C.red },
  markdownTSPunctDelimiter = { fg = C.fg },
  rustTSType = { fg = C.yellow },
  rustTSFuncMacro = { fg = C.orange },
  rustTSNamespace = { fg = C.yellow },
  rustTSConstant = { fg = C.cyan },
  rustTSKeywordFunction = { fg = C.orange },
  -- NeoTree
  NeoTreeDirectoryIcon = { fg = C.grey },
  NeoTreeRootName = { fg = C.grey, bold = true },
  NeoTreeFileName = { fg = C.fg },
  NeoTreeFileIcon = { fg = C.fg },
  NeoTreeFileNameOpened = { fg = C.green },
  NeoTreeIndentMarker = { fg = C.blue_3 },
  NeoTreeGitAdded = { fg = C.yellow },
  NeoTreeGitConflict = { fg = C.red },
  NeoTreeGitModified = { fg = C.purple },
  NeoTreeGitUntracked = { fg = C.green },
  NeoTreeNormal = { bg = C.none },
  NeoTreeNormalNC = { bg = C.none },
  NeoTreeSymbolicLinkTarget = { fg = C.cyan },
  -- Telescope
  TelescopeResultsTitle = { fg = C.green },
  TelescopePromptTitle = { fg = C.blue },
  TelescopePreviewTitle = { fg = C.purple },
  TelescopeResultsBorder = { fg = C.blue },
  TelescopePromptBorder = { fg = C.blue },
  TelescopePreviewBorder = { fg = C.blue },
  TelescopeSelectionCaret = { fg = C.purple },
  TelescopeMatching = { fg = C.yellow },
  TelescopeSelection = { bg = C.grey_5 },
  TelescopeMultiSelection = { fg = C.blue },
  TelescopeMultiIcon = { fg = C.blue },
  TelescopeNormal = { fg = C.fg, bg = C.bg },
  TelescopePreviewNormal = { fg = C.fg, bg = C.bg },
  TelescopePromptNormal = { fg = C.fg, bg = C.bg },
  TelescopeResultsNormal = { fg = C.fg, bg = C.bg },
  TelescopeBorder = { fg = C.fg },
  TelescopeTitle = { fg = C.fg },
  TelescopePromptCounter = { fg = C.grey_1 },
  TelescopePromptPrefix = { fg = C.blue },
  TelescopePreviewLine = { bg = C.grey_5 },
  TelescopePreviewMatch = { fg = C.yellow },
  TelescopePreviewPipe = { fg = C.yellow },
  TelescopePreviewCharDev = { fg = C.yellow },
  TelescopePreviewDirectory = { fg = C.blue },
  TelescopePreviewBlock = { fg = C.yellow },
  TelescopePreviewLink = { fg = C.blue },
  TelescopePreviewSocket = { fg = C.purple },
  TelescopePreviewRead = { fg = C.yellow },
  TelescopePreviewWrite = { fg = C.purple },
  TelescopePreviewExecute = { fg = C.green },
  TelescopePreviewHyphen = { fg = C.grey_1 },
  TelescopePreviewSticky = { fg = C.blue },
  TelescopePreviewSize = { fg = C.green },
  TelescopePreviewUser = { fg = C.yellow },
  TelescopePreviewGroup = { fg = C.yellow },
  TelescopePreviewDate = { fg = C.blue },
  TelescopePreviewMessage = { fg = C.fg },
  TelescopePreviewMessageFillchar = { fg = C.fg },
  TelescopeResultsClass = { fg = C.yellow },
  TelescopeResultsConstant = { fg = C.yellow },
  TelescopeResultsField = { fg = C.red },
  TelescopeResultsFunction = { fg = C.blue },
  TelescopeResultsMethod = { fg = C.blue },
  TelescopeResultsOperator = { fg = C.cyan },
  TelescopeResultsStruct = { fg = C.purple },
  TelescopeResultsVariable = { fg = C.red },
  TelescopeResultsLineNr = { fg = C.grey_1 },
  TelescopeResultsIdentifier = { fg = C.blue },
  TelescopeResultsNumber = { fg = C.orange },
  TelescopeResultsComment = { fg = C.grey_2 },
  TelescopeResultsSpecialComment = { fg = C.grey },
  TelescopeResultsDiffChange = { fg = C.none, bg = C.yellow },
  TelescopeResultsDiffAdd = { fg = C.none, bg = C.green },
  TelescopeResultsDiffDelete = { fg = C.none, bg = C.red },
  TelescopeResultsDiffUntracked = { fg = C.none, bg = C.grey_1 },
  -- GitSigns
  GitSignsAdd = { fg = C.green, bg = C.none },
  GitSignsChange = { fg = C.purple, bg = C.none },
  GitSignsDelete = { fg = C.red_1, bg = C.none },
  MoreMsg = { fg = C.green, bold = true },
  ModeMsg = { fg = C.grey, bold = true },
}
